spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cinephile

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fazlyev.cinephile.mongock.changelog
